# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ChessGame.ui'
#
# Created: Mon Apr 24 09:35:31 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1150, 853)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 200, 721))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.hallList = QtGui.QTreeWidget(self.verticalLayoutWidget)
        self.hallList.setObjectName(_fromUtf8("hallList"))
        self.hallList.setHeaderLabel("Hall")
        item_0 = QtGui.QTreeWidgetItem(self.hallList)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.verticalLayout.addWidget(self.hallList)
        self.groupChatTitle = QtGui.QLabel(self.verticalLayoutWidget)
        self.groupChatTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.groupChatTitle.setObjectName(_fromUtf8("groupChatTitle"))
        self.verticalLayout.addWidget(self.groupChatTitle)
        self.groupChatRoom = QtGui.QTextEdit(self.verticalLayoutWidget)
        self.groupChatRoom.setObjectName(_fromUtf8("groupChatRoom"))
        self.verticalLayout.addWidget(self.groupChatRoom)
        self.groupChatRoom.setStyleSheet(_fromUtf8("font-size: 11px; color: #1A1A1A; background: #FDF5E6"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sendGroupMsg = QtGui.QPushButton(self.verticalLayoutWidget)
        self.sendGroupMsg.setObjectName(_fromUtf8("sendGroupMsg"))
        self.horizontalLayout.addWidget(self.sendGroupMsg)
        self.groupChatEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.groupChatEdit.setObjectName(_fromUtf8("groupChatEdit"))
        self.horizontalLayout.addWidget(self.groupChatEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(860, 50, 280, 721))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.userRankList = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.userRankList.setObjectName(_fromUtf8("userRankList"))
        self.verticalLayout_3.addWidget(self.userRankList)
        self.scoreListWigdet = QtGui.QListWidget(self.verticalLayoutWidget_3)
        self.scoreListWigdet.setObjectName(_fromUtf8("scoreListWigdet"))
        self.verticalLayout_3.addWidget(self.scoreListWigdet)
        self.rule = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.rule.setObjectName(_fromUtf8("rule"))
        self.verticalLayout_3.addWidget(self.rule)

        self.textEdit_3 = QtGui.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.verticalLayout_3.addWidget(self.textEdit_3)

        self.textEdit_3.append(_fromUtf8('1.棋盘'))
        self.textEdit_3.append(_fromUtf8('  五子棋专用棋盘为 15×15,盘面有纵横各十五条等距离垂直交叉的平行线构成,共225个交叉点\n'))
        self.textEdit_3.append(_fromUtf8('2.下棋顺序'))
        self.textEdit_3.append(_fromUtf8('  黑先白后，第一次进房间系统随机分配黑白方，再玩一局的时候输者为黑棋\n'))
        self.textEdit_3.append(_fromUtf8('3.判定胜负'))
        self.textEdit_3.append(_fromUtf8('  最先在棋盘横向、竖向、斜向形成连续的相同颜色五个棋子的一方获胜;棋盘下满，为和棋\n'))
        self.textEdit_3.append(_fromUtf8('4.积分规则'))
        self.textEdit_3.append(_fromUtf8('  赢家得3分，输家得-1分，和棋得0分\n'))
        self.textEdit_3.setReadOnly(True)
        self.singleRoomChatTitle = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.singleRoomChatTitle.setObjectName(_fromUtf8("singleRoomChatTitle"))
        self.verticalLayout_3.addWidget(self.singleRoomChatTitle)
        self.singleChatRoom = QtGui.QTextEdit(self.verticalLayoutWidget_3)
        self.singleChatRoom.setObjectName(_fromUtf8("singleChatRoom"))
        self.verticalLayout_3.addWidget(self.singleChatRoom)
        self.singleChatRoom.setStyleSheet(_fromUtf8("font-size: 11px; color: #1A1A1A; background: #FDF5E6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.sendSingleMsg = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.sendSingleMsg.setObjectName(_fromUtf8("sendSingleMsg"))
        self.horizontalLayout_5.addWidget(self.sendSingleMsg)
        self.singleChatEdit = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.singleChatEdit.setObjectName(_fromUtf8("singleChatEdit"))
        self.horizontalLayout_5.addWidget(self.singleChatEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 50, 630, 721))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.userone = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.userone.setAlignment(QtCore.Qt.AlignRight)
        self.userone.setObjectName(_fromUtf8("userone"))
        self.verticalLayout_4.addWidget(self.userone)
        self.scoreStatus1 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.scoreStatus1.setAlignment(QtCore.Qt.AlignCenter)
        self.scoreStatus1.setObjectName(_fromUtf8("scoreStatus1"))
        self.verticalLayout_4.addWidget(self.scoreStatus1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.chessboard = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.chessboard.setMinimumSize(QtCore.QSize(480, 480))
        self.chessboard.setMaximumSize(QtCore.QSize(480, 480))
        self.chessboard.setText(_fromUtf8(""))
        self.chessboard.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.chessboard.setObjectName(_fromUtf8("chessboard"))
        self.horizontalLayout_6.addWidget(self.chessboard)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem15)
        self.usertwo = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.usertwo.setAlignment(QtCore.Qt.AlignLeft)
        self.usertwo.setObjectName(_fromUtf8("usertwo"))
        self.verticalLayout_5.addWidget(self.usertwo)
        self.scoreStatus2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.scoreStatus2.setAlignment(QtCore.Qt.AlignCenter)
        self.scoreStatus2.setObjectName(_fromUtf8("scoreStatus2"))
        self.verticalLayout_5.addWidget(self.scoreStatus2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.selectChess = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.selectChess.setObjectName(_fromUtf8("selectChess"))
        self.horizontalLayout_4.addWidget(self.selectChess)
        self.blackChess = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.blackChess.setObjectName(_fromUtf8("blackChess"))
        self.horizontalLayout_4.addWidget(self.blackChess)
        self.whiteChess = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.whiteChess.setObjectName(_fromUtf8("whiteChess"))
        self.horizontalLayout_4.addWidget(self.whiteChess)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.roomName = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.roomName.setAlignment(QtCore.Qt.AlignCenter)
        self.roomName.setObjectName(_fromUtf8("roomName"))
        self.verticalLayout_2.addWidget(self.roomName)
        self.infotext = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.infotext.setAlignment(QtCore.Qt.AlignCenter)
        self.infotext.setObjectName(_fromUtf8("infotext"))
        self.verticalLayout_2.addWidget(self.infotext)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.readyBt = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.readyBt.setObjectName(_fromUtf8("readyBt"))
        self.horizontalLayout_2.addWidget(self.readyBt)
        self.giveUpBt = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.giveUpBt.setObjectName(_fromUtf8("giveUpBt"))
        self.horizontalLayout_2.addWidget(self.giveUpBt)
        self.peaceBt = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.peaceBt.setObjectName(_fromUtf8("peaceBt"))
        self.horizontalLayout_2.addWidget(self.peaceBt)
        self.againBt = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.againBt.setObjectName(_fromUtf8("againBt"))
        self.horizontalLayout_2.addWidget(self.againBt)
        self.leaveOutBt = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.leaveOutBt.setObjectName(_fromUtf8("leaveOutBt"))
        self.horizontalLayout_2.addWidget(self.leaveOutBt)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1150, 43))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        # self.centralwidget.setStyleSheet(_fromUtf8('border-image:url("./images/timg.jpg")'))
        self.frame.setStyleSheet(_fromUtf8('background: #EE8262'))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setContentsMargins(5, 0, 5, 0)
        self.appTitleIcon = QtGui.QLabel(self.frame)
        self.appTitleIcon.setScaledContents(True)
        self.appTitleIcon.setObjectName(_fromUtf8("appIcon"))
        self.appTitleIcon.setMaximumSize(20, 20)
        self.appTitleIcon.setPixmap(QtGui.QPixmap(":/images/chesslogo.png"))
        self.horizontalLayout_3.addWidget(self.appTitleIcon)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.appName = QtGui.QLabel(self.frame)
        self.appName.setAlignment(QtCore.Qt.AlignCenter)
        self.appName.setObjectName(_fromUtf8("appName"))
        self.horizontalLayout_3.addWidget(self.appName)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.miniBt = QtGui.QPushButton(self.frame)
        self.miniBt.setMinimumSize(QtCore.QSize(25, 23))
        self.miniBt.setMaximumSize(QtCore.QSize(25, 23))
        self.miniBt.setObjectName(_fromUtf8("miniBt"))
        self.horizontalLayout_3.addWidget(self.miniBt, 0, QtCore.Qt.AlignCenter)
        self.closeBt = QtGui.QPushButton(self.frame)
        self.closeBt.setMinimumSize(QtCore.QSize(25, 23))
        self.closeBt.setMaximumSize(QtCore.QSize(25, 23))
        self.closeBt.setObjectName(_fromUtf8("closeBt"))
        self.horizontalLayout_3.addWidget(self.closeBt, 0, QtCore.Qt.AlignCenter)
        self.chessboardIcon = QtGui.QPixmap(_fromUtf8(':/images/chessboard.png'))
        self.chessboard.setPixmap(self.chessboardIcon)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/chesslogo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.appName.setStyleSheet(
            _fromUtf8("font-family: Papyrus; font-size: 18px; font-weight: bold; color:#228B22 "))
        self.textEdit_3.setStyleSheet(_fromUtf8("font-family: Papyrus; font-size: 12px; color: #8B2500; background:#FDF5E6 "))
        self.rule.setStyleSheet(_fromUtf8("font-family: Papyrus; font-size: 14px; font-weight: bold; color: #FF6A6A;"))
        self.singleRoomChatTitle.setStyleSheet(
            _fromUtf8("font-family: Papyrus; font-size: 14px; font-weight: bold; color: #FF6A6A"))
        self.groupChatTitle.setStyleSheet(
            _fromUtf8("font-family: Papyrus; font-size: 14px; font-weight: bold; color: #FF6A6A"))
        self.userRankList.setStyleSheet(
            _fromUtf8("font-family: Papyrus; font-size: 14px; font-weight: bold; color: #FF6A6A"))
        self.hallList.setStyleSheet(
            _fromUtf8("font-family: Papyrus; font-size: 12px; font-weight: bold; color: #FF6A6A; background: #FDF5E6"))
        self.userone.setStyleSheet(
            _fromUtf8("font-family: Papyrus; font-size: 12px; font-weight: bold; color: #FF6A6A"))
        self.usertwo.setStyleSheet(
            _fromUtf8("font-family: Papyrus; font-size: 12px; font-weight: bold; color: #FF6A6A"))
        self.scoreStatus1.setStyleSheet(
            _fromUtf8("font-family: Papyrus; font-size: 14px; font-weight: bold; color:#8B1A1A"))
        self.scoreStatus2.setStyleSheet(
            _fromUtf8("font-family: Papyrus; font-size: 14px; font-weight: bold; color:#8B1A1A"))
        self.scoreListWigdet.setStyleSheet(
            _fromUtf8("font-family: Papyrus; font-size: 14px; font-weight: bold; color:#9ACD32; background: #FDF5E6"))
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        # self.hallTitle.setText(_translate("MainWindow", "大厅", None))
        self.hallList.headerItem().setText(0, _translate("MainWindow", "hall", None))
        __sortingEnabled = self.hallList.isSortingEnabled()
        self.hallList.setSortingEnabled(False)
        self.hallList.topLevelItem(0).setText(0, _translate("MainWindow", "房间列表", None))
        self.hallList.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "新建子项目", None))
        self.hallList.setSortingEnabled(__sortingEnabled)
        self.groupChatTitle.setText(_translate("MainWindow", "大厅聊天室", None))
        self.groupChatTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.sendGroupMsg.setText(_translate("MainWindow", "发送", None))
        self.userRankList.setText(_translate("MainWindow", "排行榜", None))
        self.userRankList.setAlignment(QtCore.Qt.AlignCenter)
        self.rule.setText(_translate("MainWindow", "游戏规则", None))
        self.rule.setAlignment(QtCore.Qt.AlignCenter)
        self.singleRoomChatTitle.setText(_translate("MainWindow", "房间聊天室", None))
        self.singleRoomChatTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.sendSingleMsg.setText(_translate("MainWindow", "发送", None))
        self.userone.setText(_translate("MainWindow", "玩家一", None))
        self.userone.setAlignment(QtCore.Qt.AlignRight)
        self.scoreStatus1.setText(_translate("MainWindow", "", None))
        self.usertwo.setText(_translate("MainWindow", "玩家二", None))
        self.usertwo.setAlignment(QtCore.Qt.AlignLeft)
        self.scoreStatus2.setText(_translate("MainWindow", "", None))
        self.selectChess.setText(_translate("MainWindow", "您的棋子是", None))
        self.blackChess.setText(_translate("MainWindow", "黑棋", None))
        self.whiteChess.setText(_translate("MainWindow", "白棋", None))
        self.roomName.setText(_translate("MainWindow", "暂未进入房间", None))
        self.infotext.setText(_translate("MainWindow", "", None))
        self.readyBt.setText(_translate("MainWindow", "准备", None))
        self.giveUpBt.setText(_translate("MainWindow", "认输", None))
        self.peaceBt.setText(_translate("MainWindow", "和棋", None))
        self.againBt.setText(_translate("MainWindow", "再玩一局", None))
        self.leaveOutBt.setText(_translate("MainWindow", "离开", None))
        self.appName.setText(_translate("MainWindow", "Chess Game", None))
        self.miniBt.setText(_translate("MainWindow", "-", None))
        self.closeBt.setText(_translate("MainWindow", "X", None))

